export {LoginPage} from './login'
export {RegistrationPage} from './registration'
export {NotFoundPage} from './notFound'
export {ServerErrorPage} from './serverError'
export {ProfilePage} from './profile'
export {ProfileEditPage} from './profileEdit'
export {PasswordEditPage} from './passwordEdit'
export {ChatsPage} from './chats'
