export {LoginPage} from './login'
export {RegistrationPage} from './registration'
export {NotFoundPage} from './notFound'
export {ServerErrorPage} from './serverError'
export {ProfilePage} from './profile'
